-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('LEAVE_APPLIED', 'LEAVE_REQUESTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_DELETED', 'LEAVE_CANCELLED', 'TIMESHEET_SUBMITTED', 'TIMESHEET_APPROVED', 'TIMESHEET_REJECTED', 'REMINDER', 'SLA_BREACH') NOT NULL;
